name: Exmple of Using Variable Secrets
on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
        - name: Docker Login
          run: echo docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 

  deploy:
    needs: docker
    concurrency:
      group: production-deployment
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
        - name: Deploy to Server
          run: |
            echo ssh ${{ vars.DOCKER_USERNAME }}@${{ secrets.DOCKER_PASSWORD }} "deploy.sh"
            sleep 600