name: Exmple of Using Variable Secrets
on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
        - name: Docker Login
          run: echo docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 