name: Exmple of Using Variable Secrets
on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
        - name: Docker Login
          run: echo docker login -u $DOCKER_USERNAME -p ${{ secrets.DOCKER_PASSWORD }} 